MvcKutuphane/Controllers/KitapController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MvcKutuphane.Models.Entity;

namespace MvcKutuphane.Controllers
{
    public class KitapController : Controller
    {
        // GET: Kitap
        DBKUTUPHANEEntities1 db = new DBKUTUPHANEEntities1();
        public ActionResult Index(string p)
        {
            var kitaplar = from k in db.TBLKITAP select k;
            if (!string.IsNullOrEmpty(p))
            {
                kitaplar = kitaplar.Where(x => x.kitapAd.Contains(p));
            }

            //var kitaplar = db.TBLKITAP.ToList();
            return View(kitaplar.ToList());
        }
        [HttpGet]
        public ActionResult KitapEkle()
        {
            List<SelectListItem> deger1 = (from i in db.TBLKATEGORI.ToList()  //Kategori tablosundaki tüm bilgileri i'ye atıp i içindeki Ad ve ID'leri alıyoruz. DropDownListte gözükmesi için.
                                           select new SelectListItem
                                           {
                                               Text = i.kategoriAd,
                                               Value = i.ID.ToString()
                                           }).ToList();

            ViewBag.dgr1 = deger1;


            List<SelectListItem> deger2 = (from y in db.TBLYAZAR.ToList()
                                           select new SelectListItem
                                           {
                                               Text = y.yazarAd + ' ' + y.yazarSoyad,
                                               Value = y.ID.ToString()
                                           }).ToList();
            ViewBag.dgr2 = deger2;
            return View();
        }
        [HttpPost]
        public ActionResult KitapEkle(TBLKITAP p)
        {
            var ktg = db.TBLKATEGORI.Where(k => k.ID == p.TBLKATEGORI.ID).FirstOrDefault();
            var yzr = db.TBLYAZAR.Where(y => y.ID == p.TBLYAZAR.ID).FirstOrDefault();
            p.TBLKATEGORI = ktg;
            p.TBLYAZAR = yzr;
            db.TBLKITAP.Add(p);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        public ActionResult KitapSil(int id)
        {
            var kitap = db.TBLKITAP.Find(id);
            db.TBLKITAP.Remove(kitap);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        public ActionResult KitapGetir(int id)
        {
            var ktp = db.TBLKITAP.Find(id);
            List<SelectListItem> deger1 = (from i in db.TBLKATEGORI.ToList()  //Kategori tablosundaki tüm bilgileri i'ye atıp i içindeki Ad ve ID'leri alıyoruz. DropDownListte gözükmesi için.
                                           select new SelectListItem
                                           {
                                               Text = i.kategoriAd,
                                               Value = i.ID.ToString()
                                           }).ToList();

            ViewBag.dgr1 = deger1;

            List<SelectListItem> deger2 = (from y in db.TBLYAZAR.ToList()
                                           select new SelectListItem
                                           {
                                               Text = y.yazarAd + ' ' + y.yazarSoyad,
                                               Value = y.ID.ToString()
                                           }).ToList();
            ViewBag.dgr2 = deger2;

            return View("KitapGetir", ktp);
        }

        public ActionResult KitapGuncelle(TBLKITAP p)
        {
            var ktp = db.TBLKITAP.Find(p.ID);
            ktp.kitapAd = p.kitapAd;
            ktp.basimYili = p.basimYili;
            ktp.sayfaSayisi = p.sayfaSayisi;
            ktp.yayinEvi = p.yayinEvi;

            var ktg = db.TBLKATEGORI.Where(k => k.ID == p.TBLKATEGORI.ID).FirstOrDefault();
            var yzr = db.TBLYAZAR.Where(y => y.ID == p.TBLYAZAR.ID).FirstOrDefault();
            ktp.kitapKategori = ktg.ID;
            ktp.yazar = yzr.ID;
            db.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

MvcKutuphane/Views/Kitap/Index.cshtml
@using MvcKutuphane.Models.Entity
@model List<TBLKITAP>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/Layout.cshtml";
}

<h1>Kitap Listesi</h1>

@using (Html.BeginForm("Index", "Kitap", FormMethod.Get))
 {
    <div style="margin-bottom:15px; margin-top:15px;">
        <b>Aranacak Kitap Adını girin</b> <br /> @Html.TextBox("p")
        <input type="submit" value="Ara"/>
    </div>
 }


<table class="table table-bordered">
    <tr>
        <th>ID</th>
        <th>Kitap Adı</th>
        <th>Kitap Yazarı</th>
        <th>Kitap Kategorisi</th>
        <th>Basım Yılı</th>
        <th>Yayınevi</th>
        <th>Sayfa Sayısı</th>
        <th>Kitap Durumu</th>
        <th>Sil</th>
        <th>Güncelle</th>
    </tr>
    @foreach (var k in Model)
    {
        <tr>
            <td>@k.ID</td>
            <td>@k.kitapAd</td>
            <td>@k.TBLYAZAR.yazarAd&nbsp @k.TBLYAZAR.yazarSoyad</td>
            <td>@k.TBLKATEGORI.kategoriAd</td>
            <td>@k.basimYili</td>
            <td>@k.yayinEvi</td>
            <td>@k.sayfaSayisi</td>
            <td>@k.durum</td>
            <td><a href="/Kitap/KitapSil/@k.ID" class="btn btn-danger">Sil</a></td>
            <td><a href="/Kitap/KitapGetir/@k.ID" class="btn btn-success">Güncelle</a></td>


        </tr>
    }
</table>

<a href="/Kitap/KitapEkle" class="btn btn-primary">Yeni Kitap Ekle</a>

MvcKutuphane/Views/Kitap/KitapEkle.cshtml
@model MvcKutuphane.Models.Entity.TBLKITAP
@{
    ViewBag.Title = "KitapEkle";
    Layout = "~/Views/Shared/Layout.cshtml";
}

<h2>KitapEkle</h2>

<form class="form-group" method="post">
    <div></div>

    <div style="margin-top:15px">
        <label>Kitap Adı</label>
        @Html.TextBoxFor(k => k.kitapAd, new { @class = "form-control" })
    </div>
    <div style="margin-top:15px">
        <label>Kategori</label>
        @Html.DropDownListFor(k => k.TBLKATEGORI.ID,(List<SelectListItem>)ViewBag.dgr1,new {@class="form-control"})
    </div>
    <div style="margin-top:15px">
        <label>Kitap Yazarı</label>
        @Html.DropDownListFor(k => k.TBLYAZAR.ID, (List<SelectListItem>)ViewBag.dgr2, new { @class = "form-control" })
    </div>
    <div style="margin-top:15px">
        <label>Basım Yılı</label>
        @Html.TextBoxFor(k => k.basimYili, new { @class = "form-control" })
    </div>
    <div style="margin-top:15px">
        <label>Yayınevi</label>
        @Html.TextBoxFor(k => k.yayinEvi, new { @class = "form-control" })
    </div>
    <div style="margin-top:15px">
        <label>Sayfa Sayısı</label>
        @Html.TextBoxFor(k => k.sayfaSayisi , new { @class = "form-control" })
    </div>


    <div style="margin-top:15px">
        <button class="btn btn-info">Kitap Ekle</button>

    </div>





</form>

MvcKutuphane/Views/Kitap/KitapGetir.cshtml
@model  MvcKutuphane.Models.Entity.TBLKITAP
@{
    ViewBag.Title = "KitapGetir";
    Layout = "~/Views/Shared/Layout.cshtml";
}

<h2>KitapGetir</h2>

@using (Html.BeginForm("KitapGuncelle", "Kitap", FormMethod.Post))
{
<div style="margin-bottom:15px"></div>
<div class="form-group">
    <div style="margin-bottom:15px">
        <label>Yazar ID</label>
        @Html.TextBoxFor(k => k.ID, new { @class = "form-control" })
    </div>
    <div style="margin-bottom:15px">
        <label>Kitap Adı</label>
        @Html.TextBoxFor(k => k.kitapAd, new { @class = "form-control" })
    </div>
    <div style="margin-bottom:15px">
        <label>Kategori</label>
        @Html.DropDownListFor(k => k.TBLKATEGORI.ID, (List<SelectListItem>)ViewBag.dgr1, new { @class = "form-control" })
    </div>
    <div style="margin-bottom:15px">
        <label>Yazarı</label>
        @Html.DropDownListFor(k => k.TBLYAZAR.ID, (List<SelectListItem>)ViewBag.dgr2, new { @class = "form-control" })
    </div>
    <div style="margin-bottom:15px">
        <label>Basım Yılı</label>
        @Html.TextBoxFor(k => k.basimYili, new { @class = "form-control" })
    </div>
    <div style="margin-bottom:15px">
        <label>Yayın Evi</label>
        @Html.TextBoxFor(k => k.yayinEvi, new { @class = "form-control" })
    </div>
    <div style="margin-bottom:15px">
        <label>Sayfa Sayısı</label>
        @Html.TextBoxFor(k => k.sayfaSayisi, new { @class = "form-control" })
    </div>
    <button class="btn btn-warning">Kitap Bilgilerini Güncelle</button>
</div>
}